#ifndef _USER_UART_IP_USART_USER_IP_REGISTER_H_
#define _USER_UART_IP_USART_USER_IP_REGISTER_H_

#define USER_IP_INSTANCE_COUNT				(2U)


typedef struct {
	uint32_t SR;
	uint32_t DR;
	uint32_t BRR;
	uint32_t CR1;
	uint32_t CR2;
	uint32_t CR3;
	uint32_t GTPR;
} User_Ip_Usart_Type, *User_Ip_Usart_MemMapPtr;


/* Define base address USART */

#define USER_IP_UART_USART_USART1_BASEADDR    (0x40011000)
#define USER_USART1                           ((User_Ip_Uasrt_Type*)USER_IP_UART_USART_USART1_BASEADDR)

#define USER_IP_UART_USART_USART2_BASEADDR    (0x40004400)
#define USER_USART1                           ((User_Ip_Uasrt_Type*)USER_IP_UART_USART_USART1_BASEADDR)

#define USER_IP_USART_BASE_PTRS					{USER_USART1,USER_USART2}

#define USER_IP_USART_RESET_VALUE                            0x00000000u



#define USER_IP_USART_SR_PE_MASK		0x00000001u
#define USER_IP_USART_SR_PE_SHIFT		0u
#define USER_IP_USART_SR_PE_WIDTH		1u
#define USER_IP_USART_SR_FE_MASK		0x00000002u
#define USER_IP_USART_SR_FE_SHIFT		1u
#define USER_IP_USART_SR_FE_WIDTH		1u
#define USER_IP_USART_SR_NF_MASK		0x00000004u
#define USER_IP_USART_SR_NF_SHIFT		2u
#define USER_IP_USART_SR_NF_WIDTH		1u
#define USER_IP_USART_SR_ORE_MASK		0x00000008u
#define USER_IP_USART_SR_ORE_SHIFT		3u
#define USER_IP_USART_SR_ORE_WIDTH		1u
#define USER_IP_USART_SR_IDLE_MASK		0x00000010u
#define USER_IP_USART_SR_IDLE_SHIFT		4u
#define USER_IP_USART_SR_IDLE_WIDTH		1u
#define USER_IP_USART_SR_TC_MASK		0x00000020u
#define USER_IP_USART_SR_TC_SHIFT		5u
#define USER_IP_USART_SR_TC_WIDTH		1u
#define USER_IP_USART_SR_TXE_MASK		0x00000040u
#define USER_IP_USART_SR_TXE_SHIFT		6u
#define USER_IP_USART_SR_TXE_WIDTH		1u
#define USER_IP_USART_SR_LDB_MASK		0x00000080u
#define USER_IP_USART_SR_LDB_SHIFT		8u
#define USER_IP_USART_SR_LDB_WIDTH		1u
#define USER_IP_USART_SR_CTS_MASK		0x00000100u
#define USER_IP_USART_SR_CTS_SHIFT		9u
#define USER_IP_USART_SR_CTS_WIDTH		1u

#define USER_IP_USART_BRR_DIV_FRACTION_MASK			0x0000000Fu
#define USER_IP_USART_BRR_DIV_FRACTION_SHIFT		0u
#define USER_IP_USART_BRR_DIV_FRACTION_WIDTH		4u
#define USER_IP_USART_BRR_DIV_MANTISSA_MASK			0x0000FFF0u
#define USER_IP_USART_BRR_DIV_MANTISSA_SHIFT		4u
#define USER_IP_USART_BRR_DIV_MANTISSA_WIDTH		12u

#define USER_IP_USART_CR1_SBK_MASK		0x00000001u
#define USER_IP_USART_CR1_SBK_SHIFT		0u
#define USER_IP_USART_CR1_SBK_WIDTH		1u
#define USER_IP_USART_CR1_RWU_MASK		0x00000002u
#define USER_IP_USART_CR1_RWU_SHIFT		1u
#define USER_IP_USART_CR1_RWU_WIDTH		1u
#define USER_IP_USART_CR1_RE_MASK		0x00000004u
#define USER_IP_USART_CR1_RE_SHIFT		2u
#define USER_IP_USART_CR1_RE_WIDTH		1u
#define USER_IP_USART_CR1_TE_MASK		0x00000008u
#define USER_IP_USART_CR1_TE_SHIFT		3u
#define USER_IP_USART_CR1_TE_WIDTH		1u
#define USER_IP_USART_CR1_IDLEIE_MASK	0x00000010u
#define USER_IP_USART_CR1_IDLEIE_SHIFT	4u
#define USER_IP_USART_CR1_IDLEIE_WIDTH	1u
#define USER_IP_USART_CR1_RXNEIE_MASK	0x00000020u
#define USER_IP_USART_CR1_RXNEIE_SHIFT	5u
#define USER_IP_USART_CR1_RXNEIE_WIDTH  1u
#define USER_IP_USART_CR1_TCIE_MASK		0x00000040u
#define USER_IP_USART_CR1_TCIE_SHIFT	6u
#define USER_IP_USART_CR1_TCIE_WIDTH	1u
#define USER_IP_USART_CR1_TXEIE_MASK	0x00000080u
#define USER_IP_USART_CR1_TXEIE_SHIFT	7u
#define USER_IP_USART_CR1_TXEIE_WIDTH	1u
#define USER_IP_USART_CR1_PEIE_MASK		0x00000100u
#define USER_IP_USART_CR1_PEIE_SHIFT	8u
#define USER_IP_USART_CR1_PEIE_WIDTH	1u
#define USER_IP_USART_CR1_PS_MASK		0x00000200u
#define USER_IP_USART_CR1_PS_SHIFT		9u
#define USER_IP_USART_CR1_PS_WIDTH		1u
#define USER_IP_USART_CR1_PCE_MASK		0x00000400u
#define USER_IP_USART_CR1_PCE_SHIFT		10u
#define USER_IP_USART_CR1_PCE_WIDTH		1u
#define USER_IP_USART_CR1_WAKE_MASK		0x00000800u
#define USER_IP_USART_CR1_WAKE_SHIFT	11u
#define USER_IP_USART_CR1_WAKE_WIDTH	1u
#define USER_IP_USART_CR1_M_MASK		0x00001000u
#define USER_IP_USART_CR1_M_SHIFT		12u
#define USER_IP_USART_CR1_M_WIDTH		1u
#define USER_IP_USART_CR1_UE_MASK		0x00002000u
#define USER_IP_USART_CR1_UE_SHIFT		13u
#define USER_IP_USART_CR1_UE_WIDTH		1u

#define USER_IP_USART_CR2_ADD_MASK		0x0000000Fu
#define USER_IP_USART_CR2_ADD_SHIFT		0u
#define USER_IP_USART_CR2_ADD_WIDTH		4u
#define USER_IP_USART_CR2_LBDL_MASK		0x00000020u
#define USER_IP_USART_CR2_LBDL_SHIFT	5u
#define USER_IP_USART_CR2_LBDL_WIDTH	1u
#define USER_IP_USART_CR2_LBDIE_MASK	0x00000040u
#define USER_IP_USART_CR2_LBDIE_SHIFT	6u
#define USER_IP_USART_CR2_LBDIE_WIDTH	1u
#define USER_IP_USART_CR2_LBCL_MASK		0x00000100u
#define USER_IP_USART_CR2_LBCL_SHIFT	8u
#define USER_IP_USART_CR2_LBCK_WIDTH	1u
#define USER_IP_USART_CR2_CPAL_MASK		0x00000200u
#define USER_IP_USART_CR2_CPAL_SHIFT	9u
#define USER_IP_USART_CR2_CPAL_WIDTH	1u
#define USER_IP_USART_CR2_CPOL_MASK		0x00000400u
#define USER_IP_USART_CR2_CPOL_SHIFT	10U
#define USER_IP_USART_CR2_CPOL_WIDTH	1u
#define USER_IP_USART_CR2_CLKEN_MASK	0x00000800u
#define USER_IP_USART_CR2_CLKEN_SHIFT	11u
#define USER_IP_USART_CR2_CLKEN_WIDTH	1u
#define USER_IP_USART_CR2_STOP_MASK		0x00003000u
#define USER_IP_USART_CR2_STOP_SHIFT	12u
#define USER_IP_USART_CR2_STOP_WIDTH	2u
#define USER_IP_USART_CR2_LINEN_MASK	0x00004000u
#define USER_IP_USART_CR2_LINEN_SHIFT	14u
#define USER_IP_USART_CR2_LINEN_WIDTH	1u


#define USER_IP_USART_CR3_EIE_MASK		0x00000001u
#define USER_IP_USART_CR3_EIE_SHIFT		0u
#define USER_IP_USART_CR3_EIE_WIDTH		1u
#define USER_IP_USART_CR3_IREN_MASK		0x00000002u
#define USER_IP_USART_CR3_IREN_SHIFT	1u
#define USER_IP_USART_CR3_IREN_WIDTH	1u
#define USER_IP_USART_CR3_IRLP_MASK		0x00000004u
#define USER_IP_USART_CR3_IRLP_SHIFT	2u
#define USER_IP_USART_CR3_IRLP_WIDTH	1u
#define USER_IP_USART_CR3_HDSEL_MASK	0x00000008u
#define USER_IP_USART_CR3_HDSEL_SHIFT	3u
#define USER_IP_USART_CR3_HDSEL_WIDTH	1u
#define USER_IP_USART_CR3_NACK_MASK		0x00000010u
#define USER_IP_USART_CR3_NACK_SHIFT	4u
#define USER_IP_USART_CR3_NACK_WIDTH	1u
#define USER_IP_USART_CR3_SCEN_MASK		0x00000020u
#define USER_IP_USART_CR3_SCEN_SHIFT	5u
#define USER_IP_USART_CR3_SCEN_WIDTH	1u
#define USER_IP_USART_CR3_DMAR_MASK		0x00000040u
#define USER_IP_USART_CR3_DMAR_SHIFT	6u
#define USER_IP_USART_CR3_DMAR_WIDTH	1u
#define USER_IP_USART_CR3_DMAT_MASK		0x00000080u
#define USER_IP_USART_CR3_DMAT_SHIFT	7u
#define USER_IP_USART_CR3_DMAT_WIDTH	1u
#define USER_IP_USART_CR3_RTSE_MASK		0x00000100u
#define USER_IP_USART_CR3_RTSE_SHIFT	8u
#define USER_IP_USART_CR3_RTSE_WIDTH	1u
#define USER_IP_USART_CR3_CTSE_MASK		0x00000200u
#define USER_IP_USART_CR3_CTSE_SHIFT	9u
#define USER_IP_USART_CR3_CTSE_WIDTH	1u
#define USER_IP_USART_CR3_CTIE_MASK		0x00000400u
#define USER_IP_USART_CR3_CTIE_SHIFT	10u
#define USER_IP_USART_CR3_CTIE_WIDTH	1u
#define USER_IP_USART_CR3_ONEBIT_MASK	0x00000800u
#define USER_IP_USART_CR3_ONEBIT_SHIFT	11u
#define USER_IP_USART_CR3_ONEBIE_WIDTH	1u

#define USER_IP_USART_GTPR_PSC_MASK		0x000000FFu
#define USER_IP_USART_GTPR_PSC_SHIFT	0U
#define USER_IP_USART_GTPR_PSC_WIDTH	8u
#define USER_IP_USART_GTPR_GT_MASK		0x0000FF00u
#define USER_IP_USART_GTPR_GT_SHIFT		8u
#define USER_IP_USART_GTPR_GT_WIDTH		8u





#endif /* DRIVERS_ITC_MODULES_USER_UART_IP_USART_USER_IP_REGISTER_H_ */
