/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "main.h"
#include "uart1.h"

int main(void)
{
	HAL_Init();
	gpio_LED_config();
	gpio_LED_toggle(LED_GREEN);
	uart_UART1_GPIO_config();
	uart_UAR1_config();
	uint8_t c[3];
	c[0] = 0x11;
	c[1] = 0x22;
	c[2] = 0x33;
	while(1)
	{
		HAL_USART_Transmit(&huart1, c, 3, 100);
		gpio_LED_toggle(LED_GREEN);
	}
}
