#ifndef _User_Uart_Cfg_H_
#define _User_Uart_Cfg_H_


/* define channel ID */
#define USER_UART_CHANNEL_LPUART1		0U
#define USER_UART_CHANNEL_LPUART2		1U
#define USER_UART_CHANNEL_LPUART3		2U

#define USER_UART_CHANNEL_USART1		3U
#define USER_UART_CHANNEL_USART2		4U
#define USER_UART_CHANNEL_USART3		5U
#define USER_UART_CHANNEL_USART4		6U
#define USER_UART_CHANNEL_USART5		7U
#define USER_UART_CHANNEL_USART6		8U

#define USER_UART_CHANNEL_UART1			9U
#define USER_UART_CHANNEL_UART2			10U
#define USER_UART_CHANNEL_UART3			11U
#define USER_UART_CHANNEL_UART4			12U
#define USER_UART_CHANNEL_UART5			13U
#define USER_UART_CHANNEL_UART6			14U
#define USER_UART_CHANNEL_UART7			15U
#define USER_UART_CHANNEL_UART8			16U

/* define baudrate of channel user */
#define USER_UART_CHANNEL_USART1		12000000u
#define USER_UART_BAUDRATECHANE_USART1	112500

#define USER_UART_CHANNEL_USART2		12000000u
#define USER_UART_BAUDRATECHANE_USART2	112500





















#endif  /* _User_Uart_Cfg_H_ */
